// =============================================
// LIRIK SINKRON — Kasih Putih (Glenn Fredly)
// Edit angka "time" (dalam detik) untuk sesuaikan timing
// Format: { time: detik, text: "teks lirik" }
// Baris kosong text: "" = jeda antar bait
// =============================================

const lyrics = [
  { time: 23.4,  text: "Terdalam yang pernah kurasa" },
  { time: 31.3,  text: "Hasratku hanyalah untukmu" },
  { time: 36.0,  text: "Terukir manis" },
  { time: 39.0,  text: "Dalam renunganku" },
  { time: 42,  text: "Jiwamu, jiwaku menyatu" },
  { time: 45.3,  text: "Biarkanlah kurasakan" },
  { time: 50.8,  text: "Hangatnya sentuhan kasihmu" },
  { time: 57.5,  text: "Bawa daku penuhiku" },
  { time: 62.2,  text: "Berilah diriku" },
  { time: 65.5,  text: "Kasih putih di hatiku" },
  { time: 71.5,  text: "" },
  { time: 71.7,  text: "Kudatang padamu kekasihku" },
  { time: 78.7,  text: "" },
  { time: 78.9, text: "Kucurahkan isi jiwaku" },
  { time: 84.7, text: "Hanya padamu" },
  { time: 87.3, text: "Dalam air itu" },
  { time: 90, text: "Kau bawa selamanya diriku" },
  { time: 93.6, text: "" },
  { time: 93.8, text: "Biarkanlah kurasakan" },
  { time: 98.2, text: "Hangatnya sentuhan kasihmu" },
  { time: 104.9, text: "Bawa daku penuhiku" },
  { time: 109.6, text: "Berilah diriku" },
  { time: 112.6, text: "Kasih putih di hatiku" },
  { time: 119.8, text: "" },
  { time: 120.8, text: "Peluk daku oh kasihku" },
  { time: 128.1, text: "Taburiku dengan cinta" },
  { time: 136.2, text: "Biarkanlah kurasakan" },
  { time: 141, text: "Hangatnya sentuhan kasihmu" },
  { time: 147.6, text: "Bawa daku penuhiku" },
  { time: 152.4, text: "Berilah diriku kasihmu" },
  { time: 162, text: "" },
  { time: 163.4, text: "Biarkanlah kurasakan" },
  { time: 168, text: "Hangatnya sentuhan kasihmu" },
  { time: 174.6, text: "Bawa daku penuhiku" },
  { time: 180, text: "Berilah diriku" },
  { time: 183, text: "Kasih putih di hatiku" },
  { time: 190, text: "" },
  { time: 190.4, text: "Biarkanlah kurasakan" },
  { time: 195, text: "Hangatnya sentuhan kasihmu" },
  { time: 201.7, text: "Bawa daku penuhiku" },
  { time: 206.8, text: "Berilah diriku" },
  { time: 209.9, text: "Kasih putih di hatiku" },
  { time: 215, text: "" },
  { time: 216.6, text: "Kutemukan arti hidupku" },
  { time: 221.0, text: "Denganmu ✨" },
];
